In [1]:
import numpy as np

In [2]:
#1 

In [3]:
[np.arange(1,8,1)] + np.arange(0,110,10).reshape(11,1)

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [4]:
#2

In [5]:
lis = np.arange(2,22)
chet = lis[lis%2==0]
nechet = lis[lis%2!=0]
res = chet*nechet
res

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

In [6]:
#3

In [7]:
x = np.arange(0,11,1)
t3 = x * np.sin(x)
m = (0.5 < t3)
m
print(x[m])

[1 2 7 8 9]


In [8]:
#4
a = np.random.randint(0,11,(8,10))
b = np.argmin(np.sum(a,axis=1))
print(a, a[b],b)

[[ 2  7  1  9  6  6  6  6  4  1]
 [ 7  7  7  0  2  3  4  5  7  9]
 [ 9  0  2  1  4  4  9  4  5  6]
 [ 5  9  4  9 10  9  8  8  4 10]
 [ 7  1  5  7  3  9  3  2  6  3]
 [ 0  5  1  2  4  2  0  1  6  4]
 [ 5  8  6  3  6  2  0 10  5  5]
 [ 5 10  2  7  6  9  2  7  1  7]] [0 5 1 2 4 2 0 1 6 4] 5


In [9]:
#5
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
res = sum(a[a>b])
res

6

In [10]:
#6
def func1(m,n):
    arr1 = np.arange(0,n,1).reshape(int(m**0.5),int(m**0.5))
    arr1 = np.vstack((arr1,arr1))
    arr1 = np.hstack((arr1,arr1))
    return(arr1)
func1(9,9)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [11]:
#7
arr = np.arange(0,100,1)
arr = arr[(arr%2!=0)&(arr!=2)]
arr = arr[(arr%3!=0)&(arr!=3)]
arr = arr[(arr%5!=0)&(arr!=5)]
arr = arr[(arr%7!=0)&(arr!=7)]
arr

array([ 1, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
       73, 79, 83, 89, 97])

In [12]:
#8
arr = np.array(['a', 's', 'q','w','e','rr','t','y','u','i'])
call = np.array(np.random.randint(0,10,100))
arr[call]

array(['a', 'e', 'w', 'q', 'q', 'rr', 't', 's', 'e', 's', 'q', 'q', 'rr',
       'u', 's', 'i', 'q', 's', 's', 'u', 's', 'a', 't', 'w', 'u', 'e',
       'y', 'w', 'w', 'rr', 'u', 't', 'rr', 't', 's', 'rr', 'e', 't', 'u',
       'w', 't', 's', 'e', 'i', 'u', 'a', 'q', 'e', 'e', 'y', 'w', 'u',
       's', 'rr', 'a', 'e', 's', 'u', 'a', 'rr', 'q', 'u', 'y', 'rr', 'y',
       'y', 'i', 't', 'u', 'y', 'i', 'q', 'i', 'q', 't', 'rr', 'rr', 'e',
       'y', 'w', 'i', 'e', 'e', 's', 'q', 'q', 'a', 't', 'q', 'q', 'y',
       't', 'e', 'w', 'i', 's', 'rr', 'rr', 'i', 'y'], dtype='<U2')

In [13]:
#9
id = np.random.randint(0,11,size=(20,20),dtype='int')
np.diagonal(id,offset=1)

array([ 2,  9,  4,  8,  9, 10,  8,  1,  6,  0,  8,  9,  3,  7,  3,  9,  0,
        7,  3])