# Работа с таблицами Excel

## Задачи для совместного разбора

In [ ]:
import xlwings as xw
import numpy as np

1. На листе "Рецептура" файла `себестоимостьА_в1.xlsx` для области "Пшеничный хлеб" рассчитать себестоимость всех видов продукции.

In [ ]:
wb1 = xw.Book("./data/себестоимостьА_в1.xlsx")

sheet = wb1.sheets["Рецептура"]

consumption = sheet.range("G7:O10").options(np.array).value
consumption

array([[0.2  , 0.4  , 0.02 , 0.02 , 0.01 , 0.005, 0.1  ,   nan,   nan],
       [0.07 , 0.25 , 0.01 , 0.06 , 0.015,   nan, 0.06 , 0.05 ,   nan],
       [0.12 , 0.22 , 0.005,   nan, 0.009, 0.005,   nan, 0.05 , 0.03 ],
       [0.12 , 0.23 , 0.01 ,   nan, 0.015,   nan,   nan,   nan, 0.05 ]])

In [ ]:
unit_price = sheet.range("G14:O14").options(np.array).value
unit_price

array([  7.,  10., 184.,  19.,   7., 290., 105.,  83., 260.])

In [ ]:
cost_price = np.nan_to_num(consumption * unit_price).sum(axis=1)
cost_price

array([21.48 , 16.525, 17.423, 18.085])

2. Результаты расчетов 1.1 сохранить в отдельном столбце области "Пшеничный хлеб"

In [ ]:
sheet.range("T7:T10").options(transpose=True).value = cost_price
sheet.range("T6").value = "Себестоимость"

## Лабораторная работа 8.1

1. Загрузите данные из файлов `reviews_sample.csv` (__ЛР2__) и `recipes_sample.csv` (__ЛР5__) в виде `pd.DataFrame`. Обратите внимание на корректное считывание столбца(ов) с индексами. Оставьте в таблице с рецептами следующие столбцы: `id`, `name`, `minutes`, `submitted`, `description`, `n_ingredients`

In [ ]:
import pandas as pd

reviews_sample = pd.read_csv("./data/reviews_sample.csv", sep=",", parse_dates=['date'])
reviews_sample = reviews_sample.rename(columns={"Unnamed: 0": "index"})
reviews_sample = reviews_sample.set_index("index")
reviews_sample

user_id  recipe_id       date  rating  \
index                                               
370476        21752      57993 2003-05-01       5   
624300       431813     142201 2007-09-16       5   
187037       400708     252013 2008-01-10       4   
706134   2001852463     404716 2017-12-11       5   
312179        95810     129396 2008-03-14       5   
...             ...        ...        ...     ...   
1013457     1270706     335534 2009-05-17       4   
158736      2282344       8701 2012-06-03       0   
1059834      689540     222001 2008-04-08       5   
453285   2000242659     354979 2015-06-02       5   
691207       463435     415599 2010-09-30       5   

                                                    review  
index                                                       
370476   Last week whole sides of frozen salmon fillet ...  
624300   So simple and so tasty!  I used a yellow capsi...  
187037   Very nice breakfast HH, easy to make and yummy...  
706134   These are a favorite for the holidays and so e...  
312179   Excellent soup!  The tomato flavor is just gre...  
...                                                    ...  
1013457  This recipe was great! I made it last night. I...  
158736   This recipe is outstanding. I followed the rec...  
1059834  Well, we were not a crowd but it was a fabulou...  
453285   I have been a steak eater and dedicated BBQ gr...  
691207   Wonderful and simple to prepare seasoning blen...  

[126696 rows x 5 columns]

In [ ]:
recipes_sample_with_tags_ingredients = pd.read_csv("./data/recipes_sample.csv", sep=",", parse_dates=['submitted'])
recipes_sample_with_tags_ingredients = recipes_sample_with_tags_ingredients.rename(columns={"Unnamed: 0": "index"})
#recipes_sample_with_tags_ingredients = recipes_sample_with_tags_ingredients.set_index("index")
recipes_sample_with_tags_ingredients

name      id  minutes  \
0             george s at the cove  black bean soup   44123       90   
1                healthy for them  yogurt popsicles   67664       10   
2                      i can t believe it s spinach   38798       30   
3                              italian  gut busters   35173       45   
4          love is in the air  beef fondue   sauces   84797       25   
...                                             ...     ...      ...   
29995  zurie s holey rustic olive and cheddar bread  267661       80   
29996          zwetschgenkuchen  bavarian plum cake  386977      240   
29997   zwiebelkuchen   southwest german onion cake  103312       75   
29998                                   zydeco soup  486161       60   
29999        cookies by design   cookies on a stick  298512       29   

       contributor_id  submitted  n_steps  \
0               35193 2002-10-25      NaN   
1               91970 2003-07-26      NaN   
2                1533 2002-08-29      NaN   
3               22724 2002-07-27      NaN   
4                4470 2004-02-23      4.0   
...               ...        ...      ...   
29995          200862 2007-11-25     16.0   
29996          177443 2009-08-24      NaN   
29997          161745 2004-11-03      NaN   
29998          227978 2012-08-29      NaN   
29999          506822 2008-04-15      9.0   

                                             description  n_ingredients  
0      an original recipe created by chef scott meska...           18.0  
1      my children and their friends ask for my homem...            NaN  
2                these were so go, it surprised even me.            8.0  
3      my sister-in-law made these for us at a family...            NaN  
4      i think a fondue is a very romantic casual din...            NaN  
...                                                  ...            ...  
29995  this is based on a french recipe but i changed...           10.0  
29996  this is a traditional fresh plum cake, thought...           11.0  
29997  this is a traditional late summer early fall s...            NaN  
29998  this is a delicious soup that i originally fou...            NaN  
29999  i've heard of the 'cookies by design' company,...           10.0  

[30000 rows x 8 columns]

In [ ]:
recipes_sample_with_tags_ingredients.drop(["contributor_id", "n_steps"], axis=1, inplace=True)
recipes_sample_with_tags_ingredients

name      id  minutes  \
0             george s at the cove  black bean soup   44123       90   
1                healthy for them  yogurt popsicles   67664       10   
2                      i can t believe it s spinach   38798       30   
3                              italian  gut busters   35173       45   
4          love is in the air  beef fondue   sauces   84797       25   
...                                             ...     ...      ...   
29995  zurie s holey rustic olive and cheddar bread  267661       80   
29996          zwetschgenkuchen  bavarian plum cake  386977      240   
29997   zwiebelkuchen   southwest german onion cake  103312       75   
29998                                   zydeco soup  486161       60   
29999        cookies by design   cookies on a stick  298512       29   

       submitted                                        description  \
0     2002-10-25  an original recipe created by chef scott meska...   
1     2003-07-26  my children and their friends ask for my homem...   
2     2002-08-29            these were so go, it surprised even me.   
3     2002-07-27  my sister-in-law made these for us at a family...   
4     2004-02-23  i think a fondue is a very romantic casual din...   
...          ...                                                ...   
29995 2007-11-25  this is based on a french recipe but i changed...   
29996 2009-08-24  this is a traditional fresh plum cake, thought...   
29997 2004-11-03  this is a traditional late summer early fall s...   
29998 2012-08-29  this is a delicious soup that i originally fou...   
29999 2008-04-15  i've heard of the 'cookies by design' company,...   

       n_ingredients  
0               18.0  
1                NaN  
2                8.0  
3                NaN  
4                NaN  
...              ...  
29995           10.0  
29996           11.0  
29997            NaN  
29998            NaN  
29999           10.0  

[30000 rows x 6 columns]

2. Случайным образом выберите 5% строк из каждой таблицы и сохраните две таблицы на разные листы в один файл `recipes.xlsx`. Дайте листам названия "Рецепты" и "Отзывы", соответствующие содержанию таблиц. 

In [ ]:
path = "recipes.xlsx"
coeff = 0.05
writer = pd.ExcelWriter(path)
new_recipes = recipes_sample_with_tags_ingredients.sample(frac = coeff) 
wb1.sheets.add(name="Рецепты", after=wb1.sheets[0].name).range('A1').value=new_recipes

new_reviews = reviews_sample.sample(frac = coeff)
wb1.sheets.add(name="Отзывы", after="Рецепты").range('A1').value=new_reviews



3. Используя `xlwings`, добавьте на лист `Рецепты` столбец `seconds_assign`, показывающий время выполнения рецепта в секундах. Выполните задание при помощи присваивания массива значений диапазону ячеек.

In [ ]:
new_recipes["seconds_assign"]=new_recipes['minutes']*60
wb1.sheets['Рецепты'].range(chr(new_recipes.shape[1]+97).title()+'1').options(index=False).value=new_recipes["seconds_assign"] 

4. Используя `xlwings`, добавьте на лист `Рецепты` столбец `seconds_formula`, показывающий время выполнения рецепта в секундах. Выполните задание при помощи формул Excel.

In [ ]:
r=new_recipes.shape[1]+2
wb1.sheets['Рецепты'].range(1,r).value='seconds_formula'
fml = wb1.sheets['Рецепты'].range(2,r).formula='=$D2*60'
wb1.sheets['Рецепты'].range((2,r), (new_recipes.shape[0]+1,r)).formula=fml

5. Сделайте названия всех добавленных столбцов полужирными и выровняйте по центру ячейки.

In [ ]:
wb1.sheets['Рецепты'].range((1,new_recipes.shape[1]+1),(1,new_recipes.shape[1]+2)).api.Font.Bold = True
wb1.sheets['Рецепты'].range((1,new_recipes.shape[1]+1),(1,new_recipes.shape[1]+2)).api.HorizontalAlignment =  xw.constants.HAlign.xlHAlignCenter

6. Раскрасьте ячейки столбца `minutes` в соответствии со следующим правилом: если рецепт выполняется быстрее 5 минут, то цвет - зеленый; от 5 до 10 минут - жёлтый; и больше 10 - красный.

In [ ]:
from enum import Enum

class Colors(Enum):
    GREEN = (0, 255, 0)
    YELLOW = (255, 255, 0) 
    RED = (255, 0, 0)
values = wb1.sheets['Рецепты'].range("D2:D1501").value

for i in range(len(values)):
    
    if values[i] <= 5:
        wb1.sheets['Рецепты'].range(f"D{i+2}").color = Colors.GREEN.value
    
    elif 5 < values[i] <= 10:
        wb1.sheets['Рецепты'].range(f"D{i+2}").color = Colors.YELLOW.value
    
    else:
        wb1.sheets['Рецепты'].range(f"D{i+2}").color =  Colors.RED.value

7. Добавьте на лист `Рецепты`  столбец `n_reviews`, содержащий кол-во отзывов для этого рецепта. Выполните задание при помощи формул Excel.

In [ ]:
from xlwings.constants import AutoFillType

wb1.sheets['Рецепты'].range("J1").value = "n_reviews"
#sheet.range("J1").api.font_object.font_style.set('bold')

n = str(len(new_reviews) + 1)
wb1.sheets['Рецепты'].range("J2").formula = f'=COUNTIF(Отзывы!$C$2:$C${n}, "="&С2)'
wb1.sheets['Рецепты'].range('J2').api.autofill(wb1.sheets['Рецепты'].range("J2:J1501").api, AutoFillType.xlFillDefault)

True